# ----------------------------------------------
# GLOBAL
# ----------------------------------------------
site_name: Wiki Zami3l
site_url: https://wiki.zami3l.com

# ----------------------------------------------
# NAVIGATION
# ----------------------------------------------
nav:
  - Databases:
      - Install MariaDB on FreeBSD: databases/install-freebsd-mariadb.md
  - Jails:
      - In construction: jails/README.md
  - Misc:
      - IRC:
          - Use Weechat: misc/irc/use-weechat.md
          - Customization Weechat: misc/irc/custom-weechat.md
  - Pentest:
      - Crack:
          - Use John for brute force shadow: pentest/crack/use-john-bruteforce-shadow.md
  - Networking:
      - DNS:
          - Setup unbound on OpenBSD: networking/dns/setup-openbsd-unbound.md
      - Netmask Table: networking/netmask-table.md
      - Packet Analyzer:
          - Use Tcpdump: networking/packet-analyzer/use-tcpdump.md
      - Setup:
          - Setup interface on OpenBSD: networking/setup/setup-openbsd-interface.md
          - Setup VPN Mullvad on OpenBSD: networking/setup/setup-openbsd-wireguard-mullvad.md
      - Tools:
          - Use Netcat-OpenBSD: networking/tools/use-netcat-openbsd.md
  - Security:
      - Encryption:
          - Create GPG keys: security/encryption/create-gpg-keys.md
          - Use cryptetup: security/encryption/cryptsetup.md
          - Use veracrypt: security/encryption/veracrypt.md
      - SSL:
          - Diffie Hellman.md: security/ssl/diffie-hellman.md
          - Use CerBot: security/ssl/use-certbot.md
          - Create CA and CERT: security/ssl/create-ca-crt.md
      - Tools:
          - Firefox privacy plugins: security/tools/firefox-privacy-plugins.md
      - U2F:
          - Solokeys: security/u2f/solokeys.md
  - Storage:
      - In construction: storage/README.md
  - System Management:
      - Backup:
          - Extract and mount clonezilla backup: system-management/backup/extract-clonezilla-backup.md
      - FreeBSD:
          - Upgrade System & Packages: system-management/freebsd/update-upgrade-system-packages.md
          - Setup disk: system-management/freebsd/setup-freebsd-disk.md
          - Use Port Collections: system-management/freebsd/ports-collection.md
      - OpenBSD:
          - Install file sets: system-management/openbsd/install-sets.md
      - Install:
          - Install OpenBSD on APU4D4: system-management/install/install-openbsd-apu4d4.md
          - Install ArchLinux: system-management/install/install-archlinux.md
  - Tools:
      - git:
          - Conventional commits: tools/git/conventional-commits.md
          - Pushing multiple: tools/git/pushing-multiple.md
          - Setup git: tools/git/setup-git.md
      - metasploit:
          - Install metasploit on ArchLinux: tools/metasploit/install-archlinux-metasploit.md
  - Troubleshooting:
      - Redis failed opening dump.rdb: troubleshooting/redis-failed-opening-dump.md
  - Virtualization:
      - kvm:
          - Install KVM on ArchLinux: virtualization/kvm/install-archlinux-kvm.md
  - Web:
      - Install Apache on FreeBSD: web/install-freebsd-apache.md
      - Install Gitea on FreeBSD: web/install-freebsd-gitea.md
      - Install rTorrent on OpenBSD: web/install-openbsd-rtorrent.md
      - Install Nginx on OpenBSD: web/install-openbsd-nginx.md

# ----------------------------------------------
# THEME
# ----------------------------------------------
theme:
  # Thèmes
  name: material

  # langage
  language: fr

  palette:
    # Default : Clair / Slate :  Sombre
    scheme: default
    # Couleur barre
    primary: red
    # Couleur lien
    accent: red

  font:
    # Utiliser la font du système
    text: none

  features:
    # Suivi des ancres actives
    - navigation.tracking
    # Pré-Chargement
    - navigation.instant
    # Navigation par section
    - navigation.sections
    # Bouton de retour en haut
    - navigation.top
    # Cacher l'en-tête
    - header.autohide

  custom_dir: overrides

# ----------------------------------------------
# EXTRA
# ----------------------------------------------
extra_css:
  - stylesheets/extra.css

# ----------------------------------------------
# PLUGINS
# ----------------------------------------------
plugins:
  - search:
      lang:
        - fr
        - en
