# ----------------------------------------------
# GLOBAL
# ----------------------------------------------
site_name: Wiki NetUnix
site_url: https://wiki.netunix.net

# ----------------------------------------------
# NAVIGATION
# ----------------------------------------------
nav:
  - GNU/Linux:
    - ArchLinux:
      - System Management:
        - Install ArchLinux: archlinux/system-management/install.md
      - Install:
        - Docker: archlinux/install/docker.md
        - KVM: archlinux/install/kvm.md
        - Metasploit: archlinux/install/metasploit.md
  - OpenBSD:
    - System Management:
      - Install on APU4D4: openbsd/system-management/apu4d4.md
      - Install file sets: openbsd/system-management/file-sets.md
      - Install from debian: openbsd/system-management/ramdisk-from-debian.md
      - pkg: openbsd/system-management/pkg.md
    - Install:
      - Nginx: openbsd/install/nginx.md
      - rTorrent: openbsd/install/rtorrent.md
      - Unbound: openbsd/install/unbound.md
    - Network:
      - VRF: openbsd/network/vrf.md
    - Setup:
      - Network interface: openbsd/setup/network-interface.md
      - Unbound with rdomain: openbsd/setup/unbound-rdomain.md
      - Wireguard with Mullvad: openbsd/setup/wireguard-mullvad.md
  - FreeBSD:
    - System Management:
      - Boot serial console: freebsd/system-management/boot-serial-console.md
      - Install ZFS root partition: freebsd/system-management/install-zfs-root-part.md
      - Install UFS root encrypted: freebsd/system-management/install-ufs-root-encryption.md
      - Add partition: freebsd/system-management/add-partition.md
      - Packages: freebsd/system-management/packages.md
      - Ports collection: freebsd/system-management/ports-collection.md
      - Upgrade: freebsd/system-management/upgrade.md
      - ZFS Encryption: freebsd/system-management/zfs-encryption.md
      - ZFS Raid-1: freebsd/system-management/zfs-raid-1.md
      - Get src from git: freebsd/system-management/get-src.md
    - Network:
      - Setup UCARP: freebsd/network/setup-ucarp.md
    - Install:
      - Apache: freebsd/install/apache.md
      - Gitea: freebsd/install/gitea.md
      - MariaDB: freebsd/install/mariadb.md
    - Bastille:
      - Install: freebsd/bastille/install.md
  - HowTo:
    - Backup:
      - CloneZilla: howto/backup/clonezilla.md
      - Rsync: howto/backup/rsync.md
    - Database:
      - PostgreSQL Replication: howto/database/replication-postgresql.md
    - DNS:
      - Create zone DNSSEC PowerDNS: howto/dns/create-zone-dnssec-powerdns.md
    - Encryption:
      - Create GPG keys: howto/encryption/create-gpg-keys.md
      - Cryptsetup: howto/encryption/cryptsetup.md
      - Veracrypt: howto/encryption/veracrypt.md
      - Solokey: howto/encryption/solokey.md
    - Git:
      - Conventional Commits: howto/git/conventional-commits.md
      - Pushing Multiple: howto/git/pushing-multiple.md
      - Setup Git: howto/git/setup-git.md
      - Branch: howto/git/branch.md
    - Misc:
      - WeeChat: howto/misc/weechat.md
      - Custom WeeChat: howto/misc/custom-weechat.md
    - Network:
      - Netmask Table: howto/network/netmask-table.md
      - Serial console: howto/network/serial-console.md
      - NetCat: howto/network/netcat.md
      - Tcpdump: howto/network/tcpdump.md
    - SSL:
      - Certbot: howto/ssl/certbot.md
      - Create CA / Cert: howto/ssl/create-ca-crt.md
      - OpenSSL: howto/ssl/openssl.md
      - Diffie Hellman: howto/ssl/diffie-hellman.md
    - Pentest:
      - John bruteforce shadow: howto/pentest/john-bruteforce-shadow.md
  - Troubleshooting:
    - Redis failed opening dump.rdb: troubleshooting/redis-failed-opening-dump.md
    - Wireless AC9560 failed to load: troubleshooting/wireless-ac9560-failed-to-load.md

# ----------------------------------------------
# THEME
# ----------------------------------------------
theme:
  # Thèmes
  name: material

  # langage
  language: fr

  palette:
    # Default : Clair / Slate :  Sombre
    scheme: slate
    # Couleur barre
    primary: red
    # Couleur lien
    accent: red

  font:
    # Utiliser la font du système
    text: none

  features:
    # Suivi des ancres actives
    - navigation.tracking
    # Pré-Chargement
    #    - navigation.instant
    # Navigation par section
    #- navigation.sections
    # Navigation via tabs
    - navigation.tabs
    # Navigation déployée
    - navigation.expand
    # Bouton de retour en haut
    - navigation.top
    # Cacher l'en-tête
    - header.autohide

  custom_dir: overrides

# ----------------------------------------------
# EXTRA
# ----------------------------------------------
extra_css:
  - stylesheets/extra.css

# ----------------------------------------------
# PLUGINS
# ----------------------------------------------
plugins:
  - search:
      lang:
        - fr
        - en
