# ----------------------------------------------
# GLOBAL
# ----------------------------------------------
site_name: Wiki Zami3l
site_url: https://wiki.zami3l.com

# ----------------------------------------------
# NAVIGATION
# ----------------------------------------------
nav:
  - ArchLinux:
    - System Management:
      - Install OS: archlinux/system-management/install.md
    - Install:
      - Docker: archlinux/install/docker.md
      - KVM: archlinux/install/kvm.md
      - Metasploit: archlinux/install/metasploit.md
  - OpenBSD:
    - System Management:
      - Install on APU4D4: openbsd/system-management/apu4d4.md
      - Install file sets: openbsd/system-management/file-sets.md
      - PKG: openbsd/system-management/pkg.md
    - Install:
      - Nginx: openbsd/install/nginx.md
      - rTorrent: openbsd/install/rtorrent.md
      - Unbound: openbsd/install/unbound.md
    - Setup:
      - Network interface: openbsd/setup/network-interface.md
      - Wireguard with Mullvad: openbsd/setup/wireguard-mullvad.md
  - FreeBSD:
    - System Management:
      - Add partition: freebsd/system-management/add-partition.md
      - PKG: freebsd/system-management/pkg.md
      - Ports collection: freebsd/system-management/ports-collection.md
      - Upgrade: freebsd/system-management/upgrade.md
    - Install:
      - Apache: freebsd/install/apache.md
      - Gitea: freebsd/install/gitea.md
      - MariaDB: freebsd/install/mariadb.md
  - HowTo:
    - Backup:
      - CloneZilla: howto/backup/clonezilla.md
      - Rsync: howto/backup/rsync.md
    - Encryption:
      - Create GPG keys: howto/encryption/create-gpg-keys.md
      - Cryptsetup: howto/encryption/cryptsetup.md
      - Veracrypt: howto/encryption/veracrypt.md
      - Solokey: howto/encryption/solokey.md
    - Git:
      - Conventional Commits: howto/git/conventional-commits.md
      - Pushing Multiple: howto/git/pushing-multiple.md
      - Setup Git: howto/git/setup-git.md
    - Misc:
      - WeeChat: howto/misc/weechat.md
      - Custom WeeChat: howto/misc/custom-weechat.md
      - Firefox plugins: howto/misc/firefox-privacy-plugins.md
    - Networking:
      - Netmask Table: howto/networking/netmask-table.md
      - Serial console: howto/networking/serial-console.md
      - NetCat: howto/networking/netcat.md
      - Tcpdump: howto/networking/tcpdump.md
      - VRF: howto/networking/vrf.md
    - SSL:
      - Certbot: howto/ssl/certbot.md
      - Create CA / Cert: howto/ssl/create-ca-crt.md
      - OpenSSL: howto/ssl/openssl.md
      - Diffie Hellman: howto/ssl/diffie-hellman.md
    - Pentest:
      - John bruteforce shadow: howto/pentest/john-bruteforce-shadow.md
  - Troubleshooting:
    - Redis failed opening dump.rdb: troubleshooting/redis-failed-opening-dump.md

# ----------------------------------------------
# THEME
# ----------------------------------------------
theme:
  # Thèmes
  name: material

  # langage
  language: fr

  palette:
    # Default : Clair / Slate :  Sombre
    scheme: slate
    # Couleur barre
    primary: red
    # Couleur lien
    accent: red

  font:
    # Utiliser la font du système
    text: none

  features:
    # Suivi des ancres actives
    - navigation.tracking
    # Pré-Chargement
    #    - navigation.instant
    # Navigation par section
    #- navigation.sections
    # Navigation via tabs
    - navigation.tabs
    # Navigation déployée
    - navigation.expand
    # Bouton de retour en haut
    - navigation.top
    # Cacher l'en-tête
    - header.autohide

  custom_dir: overrides

# ----------------------------------------------
# EXTRA
# ----------------------------------------------
extra_css:
  - stylesheets/extra.css

# ----------------------------------------------
# PLUGINS
# ----------------------------------------------
plugins:
  - search:
      lang:
        - fr
        - en
